module Canvas
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_request')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_account_authentication_service')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_account_report')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_account')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_admin')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_analytic')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_assignment_group')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_assignment')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_collection')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_communication_channel')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_conversation')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_course')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_discussion_topic')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_enrollment')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_external_tool')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_uploaded_file')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_uploaded_folder')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_group')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_login')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_role')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_sis_import')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_service')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_submission')
  require File.join(File.dirname(__FILE__), 'shuttle/canvas_user')
end

